### PR TITLE
Modified icons and urls

### PR DESCRIPTION
**Pull request by samay-rgb**
Modified social media links in profile to open in new tab and changed icons of phone. Also added social media links in footer of successful verification email

### CODE REVIEW

**Comment by garg3133** [comment]
Phone logo you changed on the profile page are not loading for me

**Comment by samay-rgb** [comment]
Screen_Shot_2022-03-12_at_11 03 21_PM
Screenshot (419)
I've added script for the updated version of Font-awesome, since those icons weren't available in the one being used.

**Comment by samay-rgb** [comment]
Screen_Shot_2022-03-12_at_11 03 21_PM

I've added script for font awesome v5.14 since those icons weren't available in the one being used.

**Comment by samay-rgb** [comment]
Screenshot (419)

**Comment by samay-rgb** [comment]
Screenshot (419)
Screenshot of the profile page

**Pull request merged**
