### PR TITLE
UI ::  Gallery Page Update

### PR DESCRIPTION
**Pull request by garg3133**

### CODE REVIEW

**Comment by sdhiman99** [comment]
70834493-86592f80-1e20-11ea-8699-7eeb33c06a5d
try to confine these album cards within the width of page header. you can reduce the card-image size if needed.

<br><br>
Also on my phone, the background behind "gallery" heading isn't visible
image

**Comment by garg3133** [comment]
Album cards confined under the Container.






The width of bg behind "Gallery" is 100% and the image is repeated in y-direction so there's no way of bg not showing. Maybe it didn't load in your phone correctly. Please check that and also the bg behind Login page as both have same code.

**Comment by garg3133** [comment]
Fixed Masthead bg and removed some padding from above and below the Album Details page.

Before:


After:

**Comment by sdhiman99** [comment]
i'm merging this one, but look into that background image issue by seeing it your own mobile....

**Pull request merged**
